name: CPP project with shell script tests CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v1
      with: 
        submodules: recursive
    - name: Prepare build dir
      run: mkdir build
    - name: Generate build files using cmake
      run: cmake ..
      working-directory: ./build
    - name: Run make
      run: make
      working-directory: ./build
    - name: Run tests
      env:
        LANG: C
      run: ctest -VV
      working-directory: ./build/test
    - name: Prepare ASAN build dir
      run: mkdir build_asan
    - name: Generate ASAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=ASAN
      working-directory: ./build_asan
    - name: Run ASAN make
      run: make
      working-directory: ./build_asan
    - name: Run ASAN tests
      env:
        LANG: C
      run: ctest -VV
      working-directory: ./build_asan/test
    - name: Prepare USAN build dir
      run: mkdir build_usan
    - name: Generate USAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=USAN
      working-directory: ./build_usan
    - name: Run USAN make
      run: make
      working-directory: ./build_usan
    - name: Run USAN tests
      env:
        LANG: C
      run: ctest -VV
      working-directory: ./build_usan/test
